[package]
name = "socket_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shtp = { path = '../shtp' }
tokio = { version = "1.20.1", features = ["full"] }
async-trait = "*"